CREATE DATABASE APARTMENT_DB;
CREATE TABLE APARTMENT_DETAILS
(

APARTMENT_NAME VARCHAR(50),
APARTMENT_NO INT  PRIMARY KEY,
APARTMENT_SIZE INT,
APARTMENT_PRICE INT,
APARTMENT_LOCATION VARCHAR(50),
APARTMENT_PICTURE IMAGE
);
SELECT * FROM APARTMENT_DETAILS;